# Generated by Django 4.2.3 on 2025-03-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0002_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
