# Generated by Django 4.2.3 on 2025-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0003_remove_teacher_password_remove_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentcode',
            field=models.CharField(default=1, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
