# Generated by Django 4.2.3 on 2025-03-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0004_student_studentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='tello.vocabularycategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='tello.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by', to='tello.vocabularyword')),
            ],
            options={
                'unique_together': {('student', 'word')},
            },
        ),
    ]
