# Generated by Django 4.2.3 on 2025-03-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0005_vocabularycategory_vocabularyword_studentvocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField()),
                ('vocab_score', models.FloatField()),
                ('structure_sim_score', models.FloatField()),
                ('response_length', models.FloatField()),
                ('avg_engagement', models.FloatField()),
                ('final_score', models.FloatField()),
                ('prompt_interaction_ratio', models.FloatField()),
                ('prompt_interaction_count', models.IntegerField()),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tello.student')),
            ],
        ),
    ]
