# Generated by Django 5.1.7 on 2025-03-26 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0006_studentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreport',
            name='story_id',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='student',
        ),
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tello.student')),
            ],
        ),
        migrations.AddField(
            model_name='studentreport',
            name='story_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tello.storysession'),
            preserve_default=False,
        ),
    ]
