# Generated by Django 5.1.7 on 2025-03-29 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0007_remove_studentreport_story_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvocabulary',
            name='date_learned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentvocabulary',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
