# Generated by Django 5.1.7 on 2025-03-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tello', '0008_studentvocabulary_date_learned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='learned_words',
            field=models.ManyToManyField(blank=True, related_name='learned_in_sessions', to='tello.vocabularyword'),
        ),
    ]
